apiVersion: v1
kind: Service
metadata:
  name: cloud-orchestrator
  labels:
    app: cloud-orchestrator
spec:
  type: LoadBalancer
  selector:
    app: cloud-orchestrator
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  sessionAffinity: None
